name: Unit Tests & Code Standards
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
  
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer validate
        run: composer validate

      - uses: php-actions/composer@v6
        name: Install Composer dependencies
        with:
          php_version: '7.4'

      - name: Run Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: './phpunit.xml.dist'
          version: '9.5.26'
          php_version: '7.4'

      - name: Run Code Standards Check
        run: vendor/bin/phpcs